version: 0.2

phases:
    pre_build:
      commands:
        - echo Logging in to Amazon ECR.....
        - aws --version
        - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 582081142432.dkr.ecr.ap-south-1.amazonaws.com
        - REPOSITORY_URI=582081142432.dkr.ecr.ap-south-1.amazonaws.com/googleform
        - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        - IMAGE_TAG=${COMMIT_HASH:=latest}
    build:
      commands:
        - echo Build started on `date`
        - echo Building the Docker image...
        - cd backend
        - docker build -t googleform .
        - docker tag googleform:latest 582081142432.dkr.ecr.ap-south-1.amazonaws.com/googleform:latest
    post_build:
      commands:
        - echo Build completed on `date`
        - echo Pushing the Docker images...
        - docker push 582081142432.dkr.ecr.ap-south-1.amazonaws.com/googleform:latest
        - echo Writing image definitions file...
        - printf '[{"name":"googleform","imageUri":"%s"}]' googleform 582081142432.dkr.ecr.ap-south-1.amazonaws.com/googleform:latest > imagedefinitions.json

artifacts:
    files:
    - backend/imagedefinitions.json
    discard-paths: yes