version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - node -v
      - cd backend
      - npm install
  build:
    commands:
      - npm run build
      - npm run test
        