const { moduleTypes } = require('../type')

const ResponseViewReducerTypes = {
    UPDATE_IS_LOADING_FOR_GET_RESPONSE: `${moduleTypes.RESPONSE_VIEW}/UPDATE_IS_LOADING_FOR_GET_RESPONSE`,
    UPDATE_IS_LOADING_FOR_SUBMIT_RESPONSE: `${moduleTypes.RESPONSE_VIEW}/UPDATE_IS_LOADING_FOR_SUBMIT_RESPONSE`,
    UPDATE_IS_SUBMIT_RESPONSE_SUCCESSFULLY: `${moduleTypes.RESPONSE_VIEW}/UPDATE_IS_SUBMIT_RESPONSE_SUCCESSFULLY`,
    SET_RESPONSES: `${moduleTypes.RESPONSE_VIEW}/SET_RESPONSES`,
    SET_RESPONSE: `${moduleTypes.RESPONSE_VIEW}/SET_RESPONSE`,
    SET_VALIDATION_SCHEMA: `${moduleTypes.RESPONSE_VIEW}/SET_VALIDATION_SCHEMA`,
    CLEAR_RESPONSES: `${moduleTypes.RESPONSE_VIEW}/CLEAR_RESPONSES`,
    CLEAR_RESPONSE: `${moduleTypes.RESPONSE_VIEW}/CLEAR_RESPONSE`,

    UPDATE_ANSWER_IN_RESPONSE: `${moduleTypes.RESPONSE_VIEW}/UPDATE_ANSWER_IN_RESPONSE`,
    UPDATE_IS_LOADING_FOR_FILE_UPLOAD: `${moduleTypes.RESPONSE_VIEW}/UPDATE_IS_LOADING_FOR_FILE_UPLOAD`,

    UPDATE_PAGES: `${moduleTypes.RESPONSE_VIEW}/UPDATE_PAGES`,
    UPDATE_TOTAL_DATA: `${moduleTypes.RESPONSE_VIEW}/UPDATE_TOTAL_DATA`,

    UPDATE_IS_LOADING_FOR_CLEAR_RESPONSE: `${moduleTypes.RESPONSE_VIEW}/UPDATE_IS_LOADING_FOR_CLEAR_RESPONSE`,
    UPDATE_IS_CLEAR_RESPONSE_CONFIRMATION_DIALOG_OPEN: `${moduleTypes.RESPONSE_VIEW}/UPDATE_IS_CLEAR_RESPONSE_CONFIRMATION_DIALOG_OPEN`,
}

const ResponseViewActionTypes = {
    findAll: `${moduleTypes.RESPONSE_VIEW}/findAll`,
    findOne: `${moduleTypes.RESPONSE_VIEW}/findOne`,
    create: `${moduleTypes.RESPONSE_VIEW}/create`,
    findOneForm: `${moduleTypes.RESPONSE_VIEW}/findOneForm`,
    uploadFile: `${moduleTypes.RESPONSE_VIEW}/uploadFile`
}

module.exports = {
    ResponseViewReducerTypes,
    ResponseViewActionTypes
};